### ISSUE TITLE
Mail with File Attachments don't work - attachments content doesn't get serialized.

### ISSUE THREAD

**Issue by brosnic** [microsoftgraph/msgraph-sdk-typescript#853]
### Describe the bug

I am trying to send a Mail with an Image-Attachment via the Graph SDK. This is what my Test-Code looks like:
```

import { ClientSecretCredential } from "@azure/identity";
import { AzureIdentityAuthenticationProvider } from "@microsoft/kiota-authentication-azure";
import {
  createGraphServiceClient,
  GraphRequestAdapter,
} from "@microsoft/msgraph-sdk";
import { SendMailPostRequestBody } from "@microsoft/msgraph-sdk-users/users/item/sendMail/index.js";
import "@microsoft/msgraph-sdk-users";
import { FileAttachment } from "@microsoft/msgraph-sdk/models/index.js";
import fs from "fs";

const fromRecipient = "<from@mail.com>";
const toRecipient = "<to@mail.com>";

const credential = new ClientSecretCredential(
<tenantId>,
  <clientId>,
  <clientSecret>
);

// @microsoft/kiota-authentication-azure
const authProvider = new AzureIdentityAuthenticationProvider(credential, [
  "https://graph.microsoft.com/.default",
]);

const requestAdapter = new GraphRequestAdapter(authProvider);

const client = createGraphServiceClient(requestAdapter);

const fileBuffer = fs.readFileSync("test.jpeg");

const fileAttachment: FileAttachment = {
  odataType: "#microsoft.graph.fileAttachment",
  name: "test.jpg",
  contentType: "image/jpeg",
  contentBytes: fileBuffer,
  size: fileBuffer.byteLength,
};

const body: SendMailPostRequestBody = {
  message: {
    subject: "Testmail",
    body: {
      content:
        '<style type="text/css">html, p { font-size:14px !important; font-family: Arial, Helvetica, sans-serif !important; }</style><p>this is a test message</p>',
      contentType: "html",
    },
    hasAttachments: true,
    toRecipients: [
      {
        emailAddress: {
          address: toRecipient,
        },
      },
    ],
    attachments: [fileAttachment],
  },
};

try {
  const user = client.users.byUserId(fromRecipient);
  const mail = user.sendMail;
  await mail.post(body);
  console.log("done");
} catch (error) {
  console.log(error.message);
}
```

My dependencies are:

```
"dependencies": {
    "@azure/identity": "^4.10.2",
    "@microsoft/kiota-authentication-azure": "^1.0.0-preview.96",
    "@microsoft/kiota-http-fetchlibrary": "^1.0.0-preview.96",
    "@microsoft/msgraph-sdk": "^1.0.0-preview.64",
    "@microsoft/msgraph-sdk-users": "^1.0.0-preview.64",
    ...
  },
```

When I send this, I get an error with this message: 'Required property is missing.'

I debugged it and saw, that in https://github.com/microsoftgraph/msgraph-sdk-typescript/blob/main/packages/msgraph-sdk/models/index.ts the serializeFileAttachment Function only gets called with isSerializingDerivedType = true which leads to the state where "contentBytes" never gets written.

When i change isSerializingDerivedType to false in debug mode, the mail with the attachments got sent successfully!

Can you please fix that?

Thank you.

### Expected behavior

The attachment's "contentBytes" gets written.

### How to reproduce

Send a Mail with a File Attachment via Graph SDK - as shown above.

### SDK Version

1.0.0-preview.64

### Debug output

<details><summary>Click to expand log</summary>
```

Required property is missing.

```
</details>

**Comment by brosnic** [comment]
@BohrenAn thank you for your answer!
Yes I did try to encode the content with Base64, but it didn't work either.
If you look at the property type of contentBytes of the FileAttachment Interface in the typescript SDK, you'll see, that it's of type "ArrayBuffer".
<img width="996" height="450" alt="Image" src="https://github.com/user-attachments/assets/f5aa7ab1-f584-48f3-97c4-86f9913b7d64" />

The SDK should encode it later - but this code never gets called.

My workaround will be not to use the SDK and make the requests "by hand".

**Comment by brosnic** [comment]
Nevermind, I implemented the few post requests to send a message with attachments. Like that I don't need the SDK and am not dependent to the maintainers.

**Comment by okumura-pico** [comment]
Still reproduces on `1.0.0-preview.88` (current `latest`). Here is a repro that needs **no credentials and no network** — it calls the generated serializers directly, which is exactly what the request builders pass as `requestBodySerializer`.

The bug is not specific to attachments: **every derived-type-only property is dropped**. It also breaks open extensions, where the server rejects the request outright.

## Root cause

A base serializer dispatches to the derived one with `isSerializingDerivedType: true`, but the derived serializer returns immediately on that same flag, so its properties are never written.

```js
// @microsoft/msgraph-sdk/models/index.js
export function serializeAttachment(writer, attachment = {}, isSerializingDerivedType = false) {
    if (!attachment || isSerializingDerivedType) return;
    serializeEntity(writer, attachment, isSerializingDerivedType);
    writer.writeStringValue("contentType", attachment.contentType);
    // ...base properties are written here...
    switch (attachment.odataType) {
        case "#microsoft.graph.fileAttachment":
            serializeFileAttachment(writer, attachment, true);   // <-- passes true
            break;
    }
}

export function serializeFileAttachment(writer, fileAttachment = {}, isSerializingDerivedType = false) {
    if (!fileAttachment || isSerializingDerivedType) return;     // <-- returns here, always
    serializeAttachment(writer, fileAttachment, isSerializingDerivedType);
    writer.writeByteArrayValue("contentBytes", fileAttachment.contentBytes);  // never reached
    // ...
}
```

`serializeExtension` / `serializeOpenTypeExtension` have the identical shape, and so does every other discriminated type I checked.

That explains the reported symptom precisely: base properties (`name`, `contentType`, `size`) arrive, only the derived `contentBytes` is missing — so the mail is sent with an empty attachment rather than failing.

## Repro

```
npm i @microsoft/msgraph-sdk@1.0.0-preview.88 @microsoft/kiota-serialization-json
node repro.mjs
```

```js
import { JsonSerializationWriter } from "@microsoft/kiota-serialization-json";
import { serializeAttachment, serializeExtension } from "@microsoft/msgraph-sdk/models/index.js";

const toJson = (serialize, model) => {
  const writer = new JsonSerializationWriter();
  serialize(writer, model);
  return `{${new TextDecoder().decode(writer.getSerializedContent()).replace(/,$/, "")}}`;
};

// 1. FileAttachment: `contentBytes` is declared on the derived type and is dropped.
const attachment = toJson(serializeAttachment, {
  odataType: "#microsoft.graph.fileAttachment",
  name: "test.txt",
  contentType: "text/plain",
  contentBytes: new TextEncoder().encode("hello").buffer,
  size: 5,
});

// 2. OpenTypeExtension: `extensionName` is declared on the derived type and is dropped,
//    so POST /me/extensions fails with 400.
const extension = toJson(serializeExtension, {
  odataType: "#microsoft.graph.openTypeExtension",
  extensionName: "com.contoso.roamingSettings",
  additionalData: { theme: "dark" },
});

console.log("FileAttachment   :", attachment);
console.log("  contentBytes   :", attachment.includes("contentBytes") ? "present" : "MISSING");
console.log("OpenTypeExtension:", extension);
console.log("  extensionName  :", extension.includes("extensionName") ? "present" : "MISSING");
```

Actual output:

```
FileAttachment   : {"@odata.type":"#microsoft.graph.fileAttachment","contentType":"text/plain","name":"test.txt","size":5}
  contentBytes   : MISSING
OpenTypeExtension: {"@odata.type":"#microsoft.graph.openTypeExtension","theme":"dark"}
  extensionName  : MISSING
```

Expected: `contentBytes` and `extensionName` present.

## Second symptom: open extensions cannot be created

`POST /me/extensions` uses `requestBodySerializer: serializeExtension`
(`@microsoft/msgraph-sdk-users/users/item/extensions/index.js`), so the required
`extensionName` never reaches the wire and the server rejects every create:

```json
{
  "error": {
    "code": "BadRequest",
    "message": "'extensionName' or 'id' must be defined when creating a new open extension."
  }
}
```

## Possibly useful diagnostic

Calling the **derived** serializer directly produces the correct body, because the
base is then entered with `isSerializingDerivedType: false`:

```js
serializeFileAttachment(writer, model);
// "@odata.type":"#microsoft.graph.fileAttachment","contentType":"text/plain","name":"test.txt","size":5,"contentBytes":"aGVsbG8="
```

So only the base-serializer entry point is broken — which is the one every request
builder uses for these types.

## Environment

- `@microsoft/msgraph-sdk` 1.0.0-preview.88 (also 1.0.0-preview.87)
- `@microsoft/msgraph-sdk-users` 1.0.0-preview.88
- `@microsoft/kiota-serialization-json` 1.0.0-preview.103
- Node.js v26.2.0
